### ISSUE TITLE
[Help] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by DoM1niC** [Johni0702/mumble-web#115] opened 2020-05-27 06:38 UTC
I already got this error :( 

```
index.js:9 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ./node_modules/webworkify/index.js.module.exports (index.js:9)
    at ReusePool._factory (decoder-stream.js:36)
    at ReusePool../node_modules/reuse-pool/index.js.ReusePool.get (index.js:23)
    at Object../node_modules/mumble-client-codecs-browser/lib/decoder-stream.js (decoder-stream.js:39)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/mumble-client-codecs-browser/lib/index.js (index.js:13)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/mumble-client-codecs-browser/index.js (index.js:1)
    at __webpack_require__ (bootstrap:19)
```

```
[Unit]
Description=Websockify for Mumble Web Client 
After=network.target mumble.service

[Service]
User=root
Group=root
ExecStart=/usr/bin/websockify --web=/home/www/mumble-web/dist --ssl-target 9090 10.10.0.6:9191
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```

is  **--web=** required? Because I host Mumble on a other Server in my Network so Websockify runs on my Voip VM.

**Comment by streaps** [comment] 2020-05-27 07:59
Are the javascript error and the --web= question somehow related?

--web starts a webserver in websockify. If the mumble-web client files (in /home/www/mumble-web/dist) are served by another webserver, you can remove that option.

**Comment by DoM1niC** [comment] 2020-07-02 16:05
I use NGINX to make the dist Folder Public, --web= is already removed by my case I start websockify with `/usr/bin/websockify --ssl-target 9090 10.10.0.6:9191`

_Mumble / Websockify are on a other Maschine in same Network._

**URL:** https://voip.3dns.eu/dist/

**npm install** was success without errors

NGINX on Webserver 
```
server {
        listen 80;
        server_name voip.3dns.eu;
        return 301 https://voip.3dns.eu$request_uri;
}
server {
        include /usr/local/nginx/conf/conf.d/other.d/listen_ssl.conf;
        server_name voip.3dns.eu;
        include /usr/local/nginx/conf/conf.d/ssl.d/3dns.conf;

        index index.html;
        root /home/www/voip/;

        location / {
        }
        location /viewer {
        proxy_pass http://10.10.0.6;
        }
        location /mumble {
                proxy_pass http://10.10.0.6:9090;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }
}
```

**Comment by Johni0702** [comment] 2020-07-02 16:35
Duplicate of #121

**Closed by Johni0702** 2020-07-02 16:35 UTC
